ESCOMP/ESMStandardNames

- Metadata-standard-names.md
- standard_names.xml
`total_precipitation_at_surface` ==> `total_precipitation_rate_at_surface`
name suggested at CCPP Framework meeting. Review by checking Metadata-standard-names.md rendering on GitHub.
> Fix precipitation rate standard name

- Metadata-standard-names.md
- standard_names.xml
Originally, the standard name referred to (Rd/Rv -1).
modified:   Metadata-standard-names.md
modified:   standard_names.xml
> Fix standard name of (Rv/Rd -1)

- Metadata-standard-names.md
- standard_names.xml
Synchronize standard_names used in CAMDEN with input from list from WRF and NOAA SCM model.  Also get input from the CF conventions and attempt to adhere to NOAA's CCPP naming guidelines.
closes #8
> CAMDEN sync names with repo

- StandardNamesRules.rst
In these PR I clarified the use of (mass and volume) mixing ratios, as well as the representation of soil moisture. These clarifications are meant to address comments submitted during the review of  https://github.com/ESCOMP/CCPPStandardNames/pull/13.
> Clarification wrt mixing ratios

- StandardNamesRules.rst
Add a section about rules for variables to the standard name rules. In particular, provide guidance for dimensionless variables. 
Disclaimer. I created this PR on GitHub without actually rendering the rst file.
See https://github.com/ESCOMP/CCPPStandardNames/issues/19 and https://github.com/NCAR/ccpp-framework/issues/397 for discussions related to this PR.
> Update standard name rules with rules for units

- Metadata-standard-names.md
- standard_names.xml
Three standard names are wrong in the dictionary, "janic" needs to be "janjic" (thanks @dusanjovic-noaa for spotting this). 
The corresponding ccpp-physics, fv3atm and ccpp-scm PRs are:
https://github.com/NCAR/ccpp-physics/pull/766
https://github.com/NOAA-EMC/fv3atm/pull/416
https://github.com/NCAR/ccpp-scm/pull/279
For regression testing with the UFS, see https://github.com/ufs-community/ufs-weather-model/pull/892.
> Correct spelling of "janic" to "janjic"

- Metadata-standard-names.md
- StandardNamesRules.rst
- standard_names.xml
The [JCSDA JEDI software project](https://www.jcsda.org/jcsda-project-jedi) has decided to adopt the CCPP naming standard to use for model variables in its generic code. This PR adds some variable names to CCPP that are already CF-standards and are in use in JEDI.
This is my first attempt at a PR for this repository, so apologies if I haven't done it quite right. I'm happy to modify.
> Add JEDI UFO CF-compliant names

- Metadata-standard-names.md
- standard_names.xml
As discussed in the February 27th, 2023 framework meeting, scientists in NCAR CGD requested that some of the standard names related to geopotential height and reference pressure be modified to either be more explicit or to better match already existing standards.  This PR implements those requests.
Also, I wasn't sure who to request a review from, so I selected semi-randomly based off of previous PRs.  If I missed anyone, or selected someone who doesn't need to review, then please let me know.  Thanks!
> Updates to geopotential height and reference pressure

- check_xml_unique.py
- xml_tools.py
This PR modifies the xml_tools library to allow the use of python 3.7+ when using `write_standard_name_table.py`.  Also fixed the use of the `--overwrite` flag in `check_xml_unique.py`.
Fixes #30 
Fixes #31 
Ran tests with `check_xml_unique.py` and `check_xml_unique.py --overwrite` where duplicate variables were added to both the same section and to different sections of `standard_names.xml`, to make sure the script worked as expected.
Also ran `write_standard_name_table.py` on a modified `standard_names.xml` file to make sure the Markdown file was created successfully.  This was done with python 3.9.4, 3.10.8, and 2.7.17 to try and test that the script works with multiple versions, including versions newer than 3.6.
Finally, I again wasn't sure who to add as reviewers, so please feel …
> Fix bugs in python table writing and checking scripts

- .github/workflows/pull_request_ci.yml
- check_xml_unique.py
Fixes #33
Also has a second actions job to check that the markdown rendering of the standard names is up to date. It would be fairly easy to extend this to add a commit to the PR updating it if it isn't, but I haven't added that here as it wasn't really the focus.
> Add GitHub Actions CI for pull requests

- Metadata-standard-names.md
- StandardNamesRules.rst
- standard_names.xml
This pull request adds a new rule specifying that unless stated otherwise, the word `cloud` means all cloud phases and types.
Also, it was brought up by @grantfirl That the standard name `cloud_area_fraction` as used in the UFS doesn't include convective clouds, so the standard name was updated, along with standard names that appeared directly related, to specify that convective clouds are not included.
Finally, I am not strongly tied to the specific wording of either the new rule or the updated standard names, and so am happy to change them to whatever people prefer.
> Add new cloud standard name rule, and update cloud_area_fraction

- Metadata-standard-names.md
- standard_names.xml
In looking through some documentation updates, I noticed a typo in one of the standard names: "tendency" was written as "tendendy". This PR fixes this typo in the places it occurs.
> Fix typo in standard names

- Metadata-standard-names.md
- standard_names.xml
Added a new "scalar" gravitational acceleration standard name, and move the variable  version into the `state_variables` section.  
I also fixed some typos and updated some other standard names as described in the `fix typos` issue.  I should note that one standard name was changed slightly more than what was described in the issue at a scientist's request. 
Fixes #39 
Fixes #11
> Updating gravity and fixing typos

- Metadata-standard-names.md
- standard_names.xml
Adding atmospheric composition variables for JCSDA needs.
I took the freedom to change constituent to atmospheric composition as this is a more generic term and is now more widely used in the scientific community,
I reordered this section as follows:
- variable counts
- water
- trace gas
- aerosols 
It would have been better to put them in XML subsections but the python script doesn't allow this. I could however update the python script in a different PR if we think the subsections are really needed. 
Note that there redundancies in certain quantities such as for O3 and CO2 as volume mixing ratio and mole fraction is the same. I understand that some models especially on the meteorology side have O3 and CO2 concentrations as mole fractions but the chemistry modules as volume mixing ratios. …
> Adding atmospheric composition variables for JCSDA needs

- Metadata-standard-names.md
- StandardNamesRules.rst
- standard_names.xml
~~In issue https://github.com/ESCOMP/CCPPStandardNames/issues/50, the requirement to have a suffix that indicates an additional point above the model top was outlined. This PR adds the suggested suffix to the rules document and adds the `air_pressure_including_point_above_model_top` variable that uses it to the standard_names.~~
~~Im adding this as a draft PR initially for feedback on the suitability of adding such a suffix.~~
**_Updated with feedback from_** #50.  The requirement to have a suffix that indicates an additional point above the model top was outlined and discussed. This PR adds the suggested suffix (`extended_up_by_1`) to the rules document and adds the `air_pressure_extended_up_by_1` variable and `vertical_layer_dimension_extended_up_by_1` dimension to the standard_names. …
> Add including_point_above_model_top --> extended_up_by_1 suffix

- Metadata-standard-names.md
- tools/write_standard_name_table.py
This PR adds a function to apply header text conversion rules when generating internal markdown document links.
Fixes #54
> Add function to apply conversion rules to generated markdown links

- Metadata-standard-names.md
- StandardNamesRules.rst
- standard_names.xml
- tools/meta_stdname_check.py
This PR adds some new CCPP standard names that are currently being used within SIMA for NCAR idealized physics schemes.  
Along with the standard names themselves, I also added a couple extra sections for some variables that I thought wouldn't fit very nicely elsewhere.  At some point I think it would be worth discussing the organization of the standard names a little more, as there are some standard names that are listed under specific GFS DDTs but which are probably more universal than that (e.g. `mpi_rank`).  However, I don't believe this potential organizational concern needs to be resolved for this particular PR.
Finally, please note that some of the links to the new sections in the generated markdown file will be broken until PR #55 has been merged.  Thanks!
> Add new standard names from NCAR idealized physics schemes

- Metadata-standard-names.md
- standard_names.xml
This PR addresses Issue #59 
This PR adds some variable names to the CCPP Standard Names for land surface variables, in preparation for Met 
Office work on land surface DA with JEDI. I think it makes sense to add a new sub-section for these surface variables. I have added a subsection `land_surface`, but it could be a wider scope sub-section covering all surface (i.e. land, sea, sea-ice). Please advise :)
I have added the following land surface variable names, in alphabetical order (which would be nice to see elsewhere in the CCPP Standard Names list, for ease of reference):
1. `land_ice_area_fraction`
2. `mass_content_of_water_in_top_soil_layer`
3. `surface_snow_density`
4. `urban_area_fraction`
5. `volume_fraction_of_liquid_water_in_soil_at_critical_point`
6. …
> New sub-section and standard names for land surface variables

- Metadata-standard-names.md
- StandardNamesRules.rst
- standard_names.xml
This PR solves issue #61 on clarifying the use of the `_at_interface` suffix. I expanded rule number 4, which describes the use of location suffixes:
> By default (when not specified otherwise), variables are grid means or centers (defined by the host). If a variable is defined at a different physical location, a qualifier should be used to denote this. For example, to specify the vertical location of a variable with respect to vertical grid cells, the following rules apply. If ``[variable]`` doesn't have a vertical location suffix and is defined on `n` levels:
>
>   * ``[variable]_at_interface`` is defined at the interfaces between grid cells vertically, including the bottom-most and top-most interfaces. It is defined on `n+1` levels.
>   * ``[variable]_at_top_interfaces`` is defined at …
> Add a rule to clarify vertical stagger suffixes

- Metadata-standard-names.md
- StandardNamesRules.rst
- standard_names.xml
This PR extends a few variables related to atmospheric water:
- It extends the 3D mass contents to include a rain, snow, graupel and hail versions. 
- It extends the water mixing ratios of water vapor, cloud ice, cloud liquid water and rain by adding variants with the `_at_top_interfaces` vertical stagger. I only updated the mixing ratios wrt dry air and the mixing ratios wrt moist air and condensed water, as I don't need the mixing ratios wrt moist air alone.
It also adds a few water-related variables:
- Mixing ratios of total water.
- `water_vapor_mixing_ratio_wrt_moist_air_and_condensed_water_assuming_saturation` for saturated specific humidity.
- `derivative_of_ln_water_vapor_partial_pressure_assuming_saturation_wrt_air_temperature` for the log derivative of saturation vapor pressure …
> Add water variables

- Metadata-standard-names.md
- standard_names.xml
This adds four variables related to wind fluid dynamics. The names are already CF names that have not yet been added to the CCPP standard.
> Add four wind CF variables

- Metadata-standard-names.md
- standard_names.xml
This adds some new variable names, used in the JEDI system, that are mostly usual variants of existing CCPP variable names. They concern winds, temperature, and relative humidity.
~~Perhaps the newest concept introduced here is `surface_wind_from_direction`. I did not find any other existing CCPP variable names with direction expressed in degrees like this one.~~ removed from this PR
> Add miscellaneous atmosphere variables

- CODEOWNERS
Update CODEOWNERS. See in the file itself: "Order is important. The last matching pattern has the most precedence."
See right hand side for a demonstration that the current file is wrong.
> Fix CODEOWNERS so that not only ss421 gets notified/must approve

- StandardNamesRules.rst
This PR changes the rules (and the rules only) to make `surface` a suffix (`at_surface`) rather than a prefix. This proposed change was discussed in last week's CCPP framework meeting and is a departure from the CF conventions, which use `surface_` as a prefix. The motivation for this change is to maintain consistency with all other level qualifiers that are used as `_at_level` qualifier (i.e. as suffix).
> Update StandardNamesRules.rst: change`surface` prefix  to `_at_surface` suffix

- Metadata-standard-names.md
- standard_names.xml
This adds two names relating to height at surface, and modifies `surface_air_pressure` for the naming rule change coming in #72.
(I realize that there is more renaming of existing variables to be done as a product of #72, so I can remove `surface_air_pressure` from this PR if people feel it is better to do that rename in a group with the others. It's just that this name is of particular interest to the fast-approaching JEDI renaming code sprint, so I wanted to be sure to get it in.)
> Add/modify variable names related to surface height/pressure

- Metadata-standard-names.md
- standard_names.xml
This adds two pairs of wind variables for winds at the surface layer.
Note that the names here assume that the naming rule changes in #72 will be merged.
> New wind variables at surface

- Metadata-standard-names.md
- standard_names.xml
Following up on the discussion in https://github.com/ESCOMP/CCPPStandardNames/issues/77, this updates the streamfunction, velocity_potential, vorticity, and divergence names to:
`air_horizontal_streamfunction`
`air_horizontal_velocity_potential`
`air_upward_absolute_vorticity`
`air_horizontal_divergence`
Also, the description of `air_upward_absolute_vorticity` is updated to indicate that it is the kth/upward component of the curl.
> Update wind derivative/integral names

- Metadata-standard-names.md
- standard_names.xml
Found a geopotential height standard name that had the old `at_interface` suffix.  Updated it to match the current `at_interfaces` suffix rule (hopefully before the first tag).
> geopotential height standard name fix

- Metadata-standard-names.md
- StandardNamesRules.rst
- standard_names.xml
This is the first round of proposed rules changes based on our discussion last week. Also contains some corrections for misspelled standard names.
Comments and diffs on the rules changes (minus those resolved since the last discussion) can be found in this document, may be easier to parse: https://docs.google.com/document/d/19VOPWYA6RrFpeLZokmO-wSOLW6qQvZ_t2djDE4HZQoQ/edit?tab=t.0
> First rules update in v1 branch, fix misspelled standard names

- StandardNamesRules.rst
Add process suffix `_due_to_planetary_boundary_layer` as proposed new suffix in `StandardNamesRules.rst`.
This isn't exactly describing a process (i.e. is different than `due_to_convection`), but people use this or the abbreviation `due_to_PBL` a lot. Should it be even longer, i.e. `_due_to_planetary_boundary_layer_processes` ?
> Update StandardNamesRules.rst: add _due_to_planetary_boundary_layer

- Metadata-standard-names.md
- standard_names.xml
This PR modifies the existing `surface_skin_temperature` name to match the new naming rule introduced in #72. It also adds four new skin temperature variable variants. All these variables were introduced into JEDI during the October 2024 variable naming sprint.
Note a small JEDI/CCPP naming discrepancy discussed in https://github.com/ESCOMP/CCPPStandardNames/issues/83. I attempted to smooth over this difference in the long name.
> Add/modify skin temperature at surface variables.

- Metadata-standard-names.md
- standard_names.xml
This adds emissions names to the CCPP standard names
> add emissions names

- Metadata-standard-names.md
- StandardNamesRules.rst
- standard_names.xml
- tools/check_name_rules.py
- tools/write_standard_name_table.py
This is the second round of proposed rules changes based on our ongoing discussion to make both rules and names as consistent as possible. Major updates include:
- New "base_names" section, with subsections
- Convert instances of "surface_X" to "X_at_surface"
- Convert some instances of "air_X" or "X_of_air"
- Explicitly state what mass mixing ratios are with respect to in long_name
- Convert "mixing_ratio" to "water_vapor_mixing_ratio_wrt_moist_air"
- Convert "surface_albedo" to simply "albedo", "surface_roughness_length" to simply "roughness_length"
- Update construction template to include [non-instant time] and [non-current time], swap [at level] and [in medium]
- More detailed description of transformations and how they can work on multiple base names
- Add a few more transformations …
> Second rules update in v1 branch, update names, update `write_standard_name_table.py` to allow for subsections

- CODEOWNERS
This PR removes me as a code owner. The reason why I was a code owner was because of the UK Met Office involvement in the project, and I have now left the Met Office.
> Remove a code owner

- Metadata-standard-names.md
- StandardNamesRules.rst
- standard_names.xml
There are many misspellings in the existing `main` branch, not only in the `long_name` descriptions but in the `standard_name` entries themselves. This PR addresses the ones I have identified so far.
> Cherry-picked from V1 branch: fix misspellings in Standard Names

- Metadata-standard-names.md
- standard_names.xml
This PR adds in new aerosol variables needed for the Met Office LFRIC forecast model. These are the number and mass fractions for the two dust modes in the UKCA/GLOMAP aerosol model.
> Add glomap/UKCA dust mode variables

- Metadata-standard-names.md
- StandardNamesRules.rst
- standard_names.xml
- standard_names_v1_0.xsd
This PR addresses the following issues:
-  #94 Include more information on the role of "units"
- #102 Remove "kind" from standard name entries 
- Partially addresses #105: this PR removes the ambiguous term `amount` replacing it with more specific terms where needed, and includes a new section on "disallowed terms" that includes `specific_humidity` and `amount`.
In addition, this PR organizes the "constants" section alphabetically, and replaces the too-specific `dry_air_density` base name with `dry_air`, and change `dry_air_density` to `density_of_dry_air` to better fit with naming conventions in the updated rules.
- Resolves #94
- Resolves #102
> [release/v1] Fifth major update in v1 branch: Better information on units, remove `kind`, clarify disallowed terms
